server:
    port: 8082

spring:
    main:
        allow-circular-references: true
        
    application:
        name: accommodation-be

    mvc:
        hiddenmethod:
            filter:
                enabled: true
    
    profiles:
        active: 'dev'
    
    jpa:
        hibernate:
            ddl-auto: create-drop
    