server:
    port: 8082

spring:
    main:
        allow-circular-references: true
        
    application:
        name: accommodation-be

    mvc:
        hiddenmethod:
            filter:
                enabled: true
    
    profiles:
        active: 'dev'
    
    jpa:
        hibernate:
            ddl-auto: create-drop

accommodation-be:
    app:
        jwtSecret: "${JWT_SECRET_KEY}"
        jwtExpirationMs: 86400000  

external:
    flight-service-url: "http://localhost:8081"
    insurance-service-url: "http://localhost:8083"
    tour-service-url: "http://localhost:8084"
    rental-service-url: "http://localhost:8085"
    auth-service-url: "http://localhost:8081"
