server:
    port: 8082

spring:
    main:
        allow-circular-references: true
        
    application:
        name: accommodation-be

    mvc:
        hiddenmethod:
            filter:
                enabled: true
    
    profiles:
        active: 'dev'
    
    jpa:
        hibernate:
            ddl-auto: create-drop

accommodation-be:
    app:
        jwtSecret: "${JWT_SECRET_KEY}"
        jwtExpirationMs: 86400000  

external:
    profile-service-url: "http://localhost:8081"
    auth-service-url: "http://localhost:8081"
